### ISSUE TITLE
use a .gitignore to avoid including irrelevant .class/.classpath/other Java or IDE related files in the repo

### ISSUE THREAD

**Issue by rainiera** [peytones/Codeforces#1]
use my .gitignore if you want:
https://raw.githubusercontent.com/rainiera/dotfiles/master/gitignores/oneaday.gitignore

save it as .gitignore in the root folder of your repo that also has the .git file

then follow the instructions from this link:
http://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository

**Comment by peytones** [comment]
Fixed it. Thanks!
